version: "3"
services:
  ruby:
    build: ./ruby
    volumes:
      - ./ruby:/home/isucon/webapp/ruby
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    build: ./sql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    environment:
      - ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS=hoge
volumes:
  db-volume: